#!/usr/bin/env python3
import sys
import json
import numpy

infile = sys.argv[1]
outfile = open(infile.replace('.json', '.npy3'), 'wb')

numpy.ndarray.dump(numpy.array(json.load(open(infile))), outfile)
# json.dump(serialize(numpy.load(infile)), outfile)
