#!/usr/bin/env python2
import sys
import json
import numpy

infile = sys.argv[1]
outfile = open(infile.replace('.npy', '.json'), 'wb')

def serialize(stuff):
    if hasattr(stuff, '__iter__'):
        return [serialize(item) for item in stuff]
    return stuff

json.dump(serialize(numpy.load(infile)), outfile)
