tag_begin	PMID- 
tag_end	$ligne$
longueur_tag	6
condition_debut_tag	\S\S\s
AU  - 	ISIAUTHOR	$ligne$
TI  - 	ISITITLE
PT  - 	ISIDT
MH  - 	ISIkeyword	;
FAU - 	ISIAF	$ligne$
TA  - 	ISIJOURNAL
JT  - 	ISIJOURNALFull
RN  - 	ISIID	;
AB  - 	ISIABSTRACT
AD  - 	ISIC1	$ligne$	***,	[***]
AD  - 	ISIRP	,
AD  - 	ISIFU	;
nope- 	ISICR	$ligne$	,
SO  - 	ISITC
JT  - 	ISISO
DA  - 	ISIpubdate
VI  - 	ISIVolume
PG  - 	ISIPage
MH  - 	ISISC	;
PMID- 	ISIUT
PMID- 	ISIDOI
