#!/bin/sh
 
# In case this bash file is placed in another directory (e.g., /etc/init.d),
# the following line should be changed to an absolute path
DAEMON_DIR=$( cd "$(dirname "$BASH_SOURCE[0]")" && pwd)
DAEMON_SCRIPT=$DAEMON_DIR/server.py
DAEMON_NAME=nlpserver
DAEMON_ARGS= 
echo $DAEMON_SCRIPT
# DAEMON_USER=root
 
# The process ID of the script when it runs is stored here:
DAEMON_PID=/tmp/$DAEMON_NAME.pid
 
. /lib/lsb/init-functions
 
do_start () {
    log_daemon_msg "Starting system '$DAEMON_NAME' daemon..."
    start-stop-daemon --start --quiet \
        --make-pidfile --pidfile $DAEMON_PID --background \
        --startas /bin/bash -- -c "python3 $DAEMON_SCRIPT $DAEMON_ARGS > /tmp/$DAEMON_NAME.log 2>&1"
        # --exec $DAEMON_SCRIPT \
        # --user $DAEMON_USER --chuid $DAEMON_USER
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system '$DAEMON_NAME' daemon..."
    start-stop-daemon --stop --pidfile $DAEMON_PID --retry 10
    log_end_msg $?
}
 
case "$1" in
 
    start|stop)
        do_${1}
        ;;
 
    restart|reload|force-reload)
        do_stop
        do_start
        ;;
 
    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;
 
esac
exit 0