#!/bin/bash

sudo docker run \
        --name=gargamelle_box \
        -v /srv/gargantext:/srv/gargantext \
        -v /srv/gargandata:/srv/gargandata \
        -v /srv/gargantext_lib:/srv/gargantext_lib \
        -p 8000:8000 \
        -p 5432 \
        -it gargamelle:latest \
        /bin/bash -c "service postgresql start; /bin/su gargantua -c 'source /env_3-5/bin/activate && /srv/gargantext/manage.py runserver 0.0.0.0:8000'"

sudo docker rm gargamelle_box
